distro: xenial

install:
  - sudo apt-get update
  - sudo apt-get install software-properties-common
  - sudo apt-add-repository ppa:swi-prolog/stable
  - sudo apt-get update
  - sudo apt-get install swi-prolog
  
script:
  - swipl -o OurGame -c K01_G11.pl
